server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1qaz2wsx
    initialization-mode: always
    data: classpath*:../../../sql/*.sql
  sql:
    data: classpath*:../../../sql/*.sql"
    init:
      mode: always
      schema-locations: classpath*:/sql/schema.sql
      data-locations: classpath*:/sql/data.sql
