server:
  port: 8080
  servlet:
    context-path: /sml

spring:
  profiles:
    active: DEV,dev
  # active: PROD,prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres14:5432/postgres
    username: postgres
    password: secret
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath*:/sql/schema.sql
      data-locations: classpath*:/sql/data.sql

logging:
  level:
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    defaultModelsExpandDepth: -1
